stages:
  - mac
  - datapath
  - full

mac_no_stall:
  stage: mac
  script:
    - make update-ips
    - QUESTA=questa-2022.3-bt make TESTBENCH=tb_fir_datapath hw-all
    - QUESTA=questa-2022.3-bt make TESTBENCH=tb_fir_datapath run

mac_stall_0.05:
  stage: mac
  script:
    - make update-ips
    - QUESTA=questa-2022.3-bt make TESTBENCH=tb_fir_datapath hw-all
    - QUESTA=questa-2022.3-bt make TESTBENCH=tb_fir_datapath run P_STALL_GEN=0.05 P_STALL_RECV=0.05

datapath_no_stall:
  stage: datapath
  script:
    - make update-ips
    - QUESTA=questa-2022.3-bt make TESTBENCH=tb_fir_buffer_datapath hw-all
    - QUESTA=questa-2022.3-bt make TESTBENCH=tb_fir_buffer_datapath run

datapath_stall_0.05:
  stage: datapath
  script:
    - make update-ips
    - QUESTA=questa-2022.3-bt make TESTBENCH=tb_fir_buffer_datapath hw-all
    - QUESTA=questa-2022.3-bt make TESTBENCH=tb_fir_buffer_datapath run P_STALL_GEN=0.05 P_STALL_RECV=0.05

full_no_stall:
  stage: full
  script:
    - make update-ips
    - QUESTA=questa-2022.3-bt make TESTBENCH=tb_fir_top hw-all
    - PATH=/usr/pack/pulpsdk-1.0-kgf/artifactory/pulp-sdk-release/pkg/pulp_riscv_gcc/1.0.14/bin:$PATH make sw-all
    - QUESTA=questa-2022.3-bt make TESTBENCH=tb_fir_top run

full_stall_0.05:
  stage: full
  script:
    - make update-ips
    - QUESTA=questa-2022.3-bt make TESTBENCH=tb_fir_top hw-all
    - PATH=/usr/pack/pulpsdk-1.0-kgf/artifactory/pulp-sdk-release/pkg/pulp_riscv_gcc/1.0.14/bin:$PATH make sw-all
    - QUESTA=questa-2022.3-bt make TESTBENCH=tb_fir_top run P_STALL_GEN=0.05
