stages:
  - mac
  - datapath
  - full

mac_no_stall:
  stage: mac
  script:
    - make update-ips
    - QUESTA=questa-2022.3-bt make TESTBENCH=tb_fir_datapath hw-all
    - QUESTA=questa-2022.3-bt make TESTBENCH=tb_fir_datapath run

mac_stall_0.05:
  stage: mac
  script:
    - make update-ips
    - QUESTA=questa-2022.3-bt make TESTBENCH=tb_fir_datapath hw-all
    - QUESTA=questa-2022.3-bt make TESTBENCH=tb_fir_datapath run P_STALL_GEN=0.05 P_STALL_RECV=0.05

datapath_no_stall:
  stage: datapath
  script:
    - make update-ips
    - QUESTA=questa-2022.3-bt make TESTBENCH=tb_fir_full_datapath hw-all
    - QUESTA=questa-2022.3-bt make TESTBENCH=tb_fir_full_datapath run

datapath_stall_0.05:
  stage: datapath
  script:
    - make update-ips
    - QUESTA=questa-2022.3-bt make TESTBENCH=tb_fir_full_datapath hw-all
    - QUESTA=questa-2022.3-bt make TESTBENCH=tb_fir_full_datapath run P_STALL_GEN=0.05 P_STALL_RECV=0.05

full_no_stall:
  stage: full
  script:
    - make update-ips
    - QUESTA=questa-2022.3-bt make TESTBENCH=tb_fir_full hw-all
    - PATH=$PULP_RISCV_GCC_TOOLCHAIN:$PATH make sw-all
    - QUESTA=questa-2022.3-bt make TESTBENCH=tb_fir_full run

full_stall_0.05:
  stage: full
  script:
    - make update-ips
    - QUESTA=questa-2022.3-bt make TESTBENCH=tb_fir_full hw-all
    - PATH=$PULP_RISCV_GCC_TOOLCHAIN:$PATH make sw-all
    - QUESTA=questa-2022.3-bt make TESTBENCH=tb_fir_full run P_STALL_GEN=0.05
